---
- hosts: satellite.ncphotography.lan
  vars:
    myOrg: NCP
    cvs:
      - R5
      - R6
      - R7
      - R8
    leps:
      - APP
      - DB
      - WEB
      - SEC
    les:
      - DEV
      - TEST
      - QA
      - PROD
    lifecycle_envs: {}

  tasks:
    - name: create LEPs
      include_tasks: leploop.yml
      with_items:
      - "{{ leps }}"
      loop_control:
        loop_var: pathname
      


    #- name: generate sets of LEs to be created
    #  set_fact: lenvs="{{ leps|product(les)|list }}"
    #- debug: lenvs.items

    #- name: store list of LEs
    #  set_fact: lifecycle_envs="{{lifecycle_envs}} + [ {{item.join('-')}} ]"
    #  with_items: lenvs

    #- debug: var=lifecycle_envs
